# SPDX-License-Identifier: BSD-2-Clause
extraction:
  cpp:
    prepare:
      packages:
      - autoconf-archive
      - libcurl4-openssl-dev
      - libjson-c-dev
      - libssl-dev
      - uuid-dev
      - acl
    configure:
      command:
      - ./bootstrap
      - ./configure --disable-ptool-checks
    after_prepare:
    - cd "$LGTM_WORKSPACE"
    - mkdir installdir
    - git clone https://github.com/tpm2-software/tpm2-tss.git
    - cd tpm2-tss
    - ./bootstrap
    - ./configure --prefix="$LGTM_WORKSPACE/installdir/usr" --disable-doxygen-doc
    - make install
    - export PKG_CONFIG_PATH="$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
    - cd "$LGTM_WORKSPACE"
    - git clone https://github.com/tpm2-software/tpm2-tools.git
    - cd "tpm2-tools"
    - ./bootstrap
    - ./configure --prefix="$LGTM_WORKSPACE/installdir/usr"
    - make install
    - export PATH="$LGTM_WORKSPACE/installdir/usr/bin:$PATH"
    - cd "$LGTM_WORKSPACE"
